{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  labels:
    {{range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{end}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ .Values.name }}-service
            servicePort: 5678
{{- end }}