  
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}-app
    {{range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{end}}
spec:
  containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.image }}
      args:
        - "-text={{ .Values.container.text }}"