apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    {{range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{end}}
spec:
{{if .Values.ingress.enabled}}
{{else}}
  type: LoadBalancer
{{end}}
  selector:
    app: {{ .Values.name }}-app
  ports:
    - port: 5678 # Default port for image